import java.util.*;

public class TextBasedGame {
    public static void main(String[] args) {

        Scanner sc = new Scanner(System.in);

        int generatedNumber;

        //Generating a random number
        /*    Math.random() generates a random number in the range of [0.0, 1.0). So, we have
              multiplied that randomly generated number to 100.

             Since the number generated by random() function is double so we have casted it into
             int

             We have added 1 to this whole equation so that we have a range of 1 to 100.
        * */
        generatedNumber = 1 + (int)(100*Math.random());

        //User has to enter his guess to start the game.
        int userGuess;

        //User has only 5 attempts to guess the random number.
        int attempts = 5;

        System.out.println("A random number has been generated in the range of 1 to 100.");
        do {
            System.out.println("You currently have " + attempts + " attempts left.");
            System.out.println("Now make a guess by entering a number : ");
            userGuess = sc.nextInt();
            if (userGuess==generatedNumber){
                System.out.println("Congratulations!!!! You guessed it right. The generated was indeed " + generatedNumber + ". You have won the game.");
                break;
            }

            else if (userGuess > generatedNumber) {
                System.out.println("You have guessed high number!!! Make your guess again.");
                attempts--;
            }

            else if (userGuess < generatedNumber) {
                System.out.println("You have guessed low number!!! Make your guess again.");
                attempts--;
            }

            if (attempts == 0){
                System.out.println("You have wasted all your attempt. You lost the game. The generated number was " + generatedNumber + ".");
            }

        }while (userGuess!= generatedNumber && attempts!=0);

    }
}
